export const demoClients = [
  { id: '1', name: 'John Smith', email: 'john@smithplumbing.co.uk', phone: '07700 123456', company: 'Smith Plumbing', address: '45 Oak Lane, Manchester', _count: { quotes: 2 } },
  { id: '2', name: 'Sarah Williams', email: 'sarah@williamselectrical.co.uk', phone: '07700 234567', company: 'Williams Electrical', address: '78 Elm Street, Birmingham', _count: { quotes: 1 } },
  { id: '3', name: 'Mike Johnson', email: 'mike@johnsonbuilders.co.uk', phone: '07700 345678', company: 'Johnson Builders', address: '12 Cedar Road, Leeds', _count: { quotes: 1 } },
  { id: '4', name: 'Emma Brown', email: 'emma@browncarpentry.co.uk', phone: '07700 456789', company: 'Brown Carpentry', address: '99 Pine Avenue, Bristol', _count: { quotes: 1 } },
  { id: '5', name: 'David Lee', email: 'david@leeroofing.co.uk', phone: '07700 567890', company: 'Lee Roofing', address: '33 Maple Drive, London', _count: { quotes: 1 } },
];

export const demoQuotes = [
  {
    id: '1',
    quoteNumber: 'Q-0001',
    title: 'Bathroom Renovation',
    status: 'sent',
    validUntil: '2026-07-13',
    subtotal: 2725,
    vatRate: 20,
    vatAmount: 545,
    total: 3270,
    client: { name: 'John Smith', company: 'Smith Plumbing' },
    items: [
      { id: '1', description: 'Remove old bathroom suite', quantity: 1, unitPrice: 350, total: 350 },
      { id: '2', description: 'New toilet, basin & bath', quantity: 1, unitPrice: 1200, total: 1200 },
      { id: '3', description: 'Tiling (walls & floor)', quantity: 15, unitPrice: 45, total: 675 },
      { id: '4', description: 'Plumbing connections', quantity: 1, unitPrice: 500, total: 500 },
    ],
    createdAt: '2026-06-12',
  },
  {
    id: '2',
    quoteNumber: 'Q-0002',
    title: 'Kitchen Extension Wiring',
    status: 'accepted',
    validUntil: '2026-07-13',
    subtotal: 4250,
    vatRate: 20,
    vatAmount: 850,
    total: 5100,
    client: { name: 'Sarah Williams', company: 'Williams Electrical' },
    items: [
      { id: '1', description: 'Full rewire for extension', quantity: 1, unitPrice: 2800, total: 2800 },
      { id: '2', description: 'Additional sockets (10x)', quantity: 10, unitPrice: 85, total: 850 },
      { id: '3', description: 'Consumer unit upgrade', quantity: 1, unitPrice: 450, total: 450 },
      { id: '4', description: 'Testing & certification', quantity: 1, unitPrice: 200, total: 200 },
    ],
    createdAt: '2026-06-11',
  },
  {
    id: '3',
    quoteNumber: 'Q-0003',
    title: 'Garden Wall Repair',
    status: 'draft',
    validUntil: '2026-07-13',
    subtotal: 1285,
    vatRate: 20,
    vatAmount: 257,
    total: 1542,
    client: { name: 'Mike Johnson', company: 'Johnson Builders' },
    items: [
      { id: '1', description: 'Demolish damaged section', quantity: 3, unitPrice: 150, total: 450 },
      { id: '2', description: 'Rebuild with new blocks', quantity: 3, unitPrice: 200, total: 600 },
      { id: '3', description: 'Repointing', quantity: 8, unitPrice: 35, total: 280 },
    ],
    createdAt: '2026-06-10',
  },
  {
    id: '4',
    quoteNumber: 'Q-0004',
    title: 'Custom Bookshelf Installation',
    status: 'viewed',
    validUntil: '2026-07-13',
    subtotal: 1120,
    vatRate: 20,
    vatAmount: 224,
    total: 1344,
    client: { name: 'Emma Brown', company: 'Brown Carpentry' },
    items: [
      { id: '1', description: 'Custom oak bookshelf (3m)', quantity: 1, unitPrice: 850, total: 850 },
      { id: '2', description: 'Wall mounting & brackets', quantity: 1, unitPrice: 150, total: 150 },
      { id: '3', description: 'Finishing & staining', quantity: 1, unitPrice: 120, total: 120 },
    ],
    createdAt: '2026-06-09',
  },
  {
    id: '5',
    quoteNumber: 'Q-0005',
    title: 'Flat Roof Replacement',
    status: 'sent',
    validUntil: '2026-07-13',
    subtotal: 1780,
    vatRate: 20,
    vatAmount: 356,
    total: 2136,
    client: { name: 'David Lee', company: 'Lee Roofing' },
    items: [
      { id: '1', description: 'Remove old felt roof', quantity: 25, unitPrice: 15, total: 375 },
      { id: '2', description: 'Install EPDM rubber roof', quantity: 25, unitPrice: 45, total: 1125 },
      { id: '3', description: 'Fascia & guttering', quantity: 1, unitPrice: 380, total: 380 },
      { id: '4', description: 'Insulation upgrade', quantity: 25, unitPrice: 12, total: 300 },
    ],
    createdAt: '2026-06-08',
  },
];

export const demoStats = {
  totalQuotes: 5,
  sentQuotes: 2,
  acceptedQuotes: 1,
  conversionRate: 20.0,
  totalRevenue: 5100,
  totalClients: 5,
};
